server:
  port: 9001
spring: # 服務名稱（SpringCloud調用時才會用到）
  application:
    name: microservice-user
  datasource:
    #url: jdbc:mysql://localhost:3306/SPRING_CLOUD_TEST?characterEncoding=UTF8
    url: jdbc:mysql://localhost:3306/SPRING_CLOUD_TEST?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sa123456
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect  
  sql: # 自動塞初始資料
    init:
      mode: always
#      schema-locations:
#      - "classpath*:mySchema.sql"
      data-locations:
      - 'classpath*:myImportData.sql'
